services:

  backend:
    build: ../../backend

    environment:
      APP_ENV: production

  mongodb:
    image: mongo:7
    env_file:
      - ../../.env

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

    volumes:
      - mongo-prod-data:/data/db
      - ../../mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  nginx:
    image: nginx:alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - backend

volumes:
  mongo-prod-data: