name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create .env
        run: |
          cat > .env <<'EOF'
          MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }}
          MONGO_DB=${{ vars.MONGO_DB }}
          DB_NAME=${{ vars.DB_NAME }}
          MONGO_APP_USERNAME=${{ secrets.MONGO_APP_USERNAME }}
          MONGO_APP_PASSWORD=${{ secrets.MONGO_APP_PASSWORD }}
          MONGO_URI=${{ secrets.MONGO_URI }}
          EOF

      - name: Build containers
        run: docker compose -f docker/prod/docker-compose.yml up -d --build

      - name: Wait for backend
        run: |
          until curl -f http://localhost/health; do
            sleep 2
          done

      - name: Test API
        run: |
          curl -f http://localhost/api/books

      - name: Show logs if failed
        if: failure()
        run: docker compose -f docker/prod/docker-compose.yml logs