name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    # runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug Current Directory
        run: |
          pwd
          ls -la

      - name: Create .env
        run: |
          echo "MONGO_ROOT_USERNAME=${{ secrets.MONGO_ROOT_USERNAME }}" >> .env
          echo "MONGO_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }}" >> .env
          
          echo "MONGO_DB=$MONGO_DB" >> .env
          echo "MONGO_APP_USERNAME=${{ secrets.MONGO_APP_USERNAME }}" >> .env
          echo "MONGO_APP_PASSWORD=${{ secrets.MONGO_APP_PASSWORD }}" >> .env
          
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> backend/.env
          echo "DB_NAME=$DB_NAME" >> backend/.env

      - name: Deploy Docker
        run: |
          docker compose \
            --env-file .env \
            -f docker/prod/docker-compose.yml \
            up -d --build

      # - name: Deploy via SSH
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}

      #     script: |
      #       cd ~/apps/REPO_NAME
      #       git pull
      #       docker compose up -d --build